### ISSUE TITLE
Use more restrictive access control with AWS

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/rails-paperclip-s3-08#2]
See https://github.com/ga-wdi-boston/js-express-multer#aws-access-control---follow-along for a possible example.

**Comment by GA-MEB** [comment]
Added a reference to the `multer` repo to the lesson; seemed to go fine, though if we spin those directions out into a separate repo, it might be a good idea to trade some text for some pictures, since the AWS interface has _way_ too many options, and finding what you want can be tricky.
